### ISSUE TITLE
Inconsistency in Bus implementation

### ISSUE THREAD

**Issue by RolandLevai** [UniObuda2016Osz/MainLine#2]
Parameter name is incorrect in Bus.java in the setter below. 
Team FJKKL could fix this after sprint1, because we have to modify the Bus anyway (we'll implement a listener pattern on this class).

public void setBrakePedal(int **gasPedal**){
        if(**gasPedal**< 100 && **gasPedal** > 0)
            this.brakePedal = **gasPedal**;
        else if(**gasPedal** > 0)
            this.brakePedal = 100;
        else
            this.brakePedal = 0;
    }

**Comment by RolandLevai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bus should implement a listener pattern](https://trello.com/c/aZHv3pxw/13-bus-should-implement-a-listener-pattern)

**Comment by ravaszla** [comment]
Whoops, copy-paste error. Thanks for noticing! I will update it shortly.
